(function(g){var window=this;var V4=function(a,b,c){var d=b.xa();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Bc(c?c:"mqdefault.jpg");var f=b instanceof g.fB&&b.lengthSeconds?g.xM(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.cE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.fB?b.va:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.dk||g.gN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Sh(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.dE&&(d.playlist_length=b.getLength());a.update(d)},W4=function(a){g.V.call(this,{D:"div",
Y:["ytp-upnext","ytp-player-content"],M:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Up Next"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",M:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",M:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",M:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",M:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",M:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",W:"Auto-play is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.V({D:"button",Y:["ytp-upnext-cancel-button","ytp-button"],M:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.C(this,this.B);this.B.ia("click",this.vK,this);this.B.ba(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.I(this.an,5E3,this);g.C(this,this.G);this.H=0;g.WL(this.u,this.element,this,18788);this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.eM);this.pA();this.L(a,"autonavvisibility",
this.pA);this.L(a,"mdxnowautoplaying",this.wL);this.L(a,"mdxautoplaycanceled",this.xL);this.L(a,"mdxautoplayupnext",this.FC);3==this.u.getPresentingPlayerType()&&(a=(a=g.DL(g.vL(this.u)))?a.aF():null)&&this.FC(a);g.K(this.element,"ytp-upnext-mobile",this.u.N().o)},X4=function(a,b){if(!a.w){g.Xo("a11y-announce","Up Next "+a.A.title);
a.H=(0,g.N)();a.w=new g.I((0,g.x)(a.oq,a,b),25);a.oq(b);var c=b||g.R(a.u.N().experiments,"autoplay_time")||1E4;a.u.ma("onAutonavCoundownStarted",c)}g.On(a.element,"ytp-upnext-autoplay-paused")},Z4=function(a){Y4(a);
a.H=(0,g.N)();a.oq();g.J(a.element,"ytp-upnext-autoplay-paused")},Y4=function(a){a.w&&(a.w.dispose(),a.w=null)},$4=function(a,b){b=void 0===b?!1:b;
if(g.Q(a.u.N().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.A.xa(),a.an(),a.C=new Notification("Up Next",{body:c.title,icon:c.Bc()}),a.F=a.L(a.C,"click",a.VL),a.G.start())}Y4(a);a.u.nextVideo(!1,b)},a5=function(a,b){g.V.call(this,{D:"div",
Y:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},Tta=function(a){a5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.V({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",M:{src:b.Od}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.C(this,this.u);this.u.ba(this.element);this.subscribeButton=new g.yQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.wg,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.subscribeButton);this.subscribeButton.ba(this.u.o["html5-subscribe-button-container"]);
this.hide()},b5=function(a){var b=a.N(),c=g.Mv||g.zh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",Y:e,M:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",M:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",Y:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",Y:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.w=d;this.api=a;this.u=new g.O(this);g.C(this,this.u);this.ia("click",this.onClick);this.ia("keypress",this.B);this.u.L(a,"videodatachange",this.A);g.XL(a,this.element,this);this.A()},Uta=function(a){var b=a.suggestion.xa().videoId,c=a.suggestion.getPlaylistId();
(g.UT(a.api.app,b,a.suggestion.Lb,c,void 0,void 0)||a.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.ZL(a.api,a.element)},c5=function(a){a5.call(this,a,"videowall-endscreen");
var b=this;this.aa=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.w=new g.O(this);g.C(this,this.w);this.F=new g.I(function(){g.J(b.element,"ytp-show-tiles")},0);
g.C(this,this.F);var c=new g.V({D:"button",Y:["ytp-button","ytp-endscreen-previous"],M:{"aria-label":"Previous"},K:[g.FM()]});g.C(this,c);c.ba(this.element);c.ia("click",this.pH,this);this.table=new g.DC({D:"div",I:"ytp-endscreen-content"});g.C(this,this.table);this.table.ba(this.element);c=new g.V({D:"button",Y:["ytp-button","ytp-endscreen-next"],M:{"aria-label":"Next"},K:[g.GM()]});g.C(this,c);c.ba(this.element);c.ia("click",this.oH,this);this.u=new W4(a);g.C(this,this.u);g.UL(this.player,this.u.element,
4);this.hide()},d5=function(a){return g.VL(a.player)&&a.Vv()&&!a.B},Vta=function(a,b){return(0,g.Fc)(b.suggestions,function(c){c=g.MO(a.aa.N(),c);
g.C(a,c);return c})},e5=function(a){var b=a.Gs();
b!==a.H&&(a.H=b,a.player.S("autonavvisibility"))},f5=function(a){g.gM.call(this,a);
this.endScreen=null;this.listeners=new g.O(this);g.C(this,this.listeners);this.o=a.N();Wta(a)?this.endScreen=new c5(this.player):this.o.Ia?this.endScreen=new Tta(this.player):this.endScreen=new a5(this.player);g.C(this,this.endScreen);g.UL(this.player,this.endScreen.element,4);this.JB();this.listeners.L(a,"videodatachange",this.JB,this);this.listeners.L(a,g.bE("endscreen"),this.mH,this);this.listeners.L(a,"crx_endscreen",this.NK,this)},Wta=function(a){a=a.N();
return a.Ha&&!a.Ia};
g.r(W4,g.V);g.h=W4.prototype;g.h.an=function(){this.C&&(this.G.stop(),this.Va(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.pA=function(){g.HC(this,g.wL(this.u));g.$L(this.u,this.element,g.wL(this.u))};
g.h.VL=function(){window.focus();this.an()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.oq=function(a){a=a||g.R(this.u.N().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.N)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?$4(this,!0):this.w&&this.w.start()};
g.h.eM=function(a){!g.ye(this.B.element,g.Dp(a))&&g.mN(a,this.u)&&$4(this)};
g.h.vK=function(){g.yL(this.u,!0)};
g.h.wL=function(a){this.u.getPresentingPlayerType();this.show();X4(this,a)};
g.h.FC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.xa().videoId==a.xa().videoId||(this.A=a,V4(this,a,"hqdefault.jpg"))};
g.h.xL=function(){this.u.getPresentingPlayerType();Y4(this);this.hide()};
g.h.X=function(){Y4(this);this.an();g.V.prototype.X.call(this)};g.r(a5,g.V);g.h=a5.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.Vv=function(){return!1};
g.h.Gs=function(){return!1};
g.h.jy=function(){return!1};g.r(Tta,a5);g.r(b5,g.V);b5.prototype.onClick=function(a){g.mN(a,this.api,this.w,this.suggestion.Lb||void 0)&&Uta(this)};
b5.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.Ip(a)||(Uta(this),g.Hp(a))}};
b5.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.N();this.w=a.xc?!1:b.u};g.r(c5,a5);g.h=c5.prototype;g.h.create=function(){a5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=Vta(this,a),this.videoData=a);this.qg();this.w.L(this.player,"appresize",this.qg);this.w.L(this.player,"onVideoAreaChange",this.qg);this.w.L(this.player,"videodatachange",this.qH);this.w.L(this.player,"autonavchange",this.Hs);this.w.L(this.player,"autonavcancel",this.nH);a=this.videoData.autonavState;a!==this.G&&this.Hs(a);this.w.L(this.element,"transitionend",this.yN)};
g.h.destroy=function(){g.Br(this.w);g.Je(this.stills);this.stills=[];this.suggestions=null;a5.prototype.destroy.call(this);g.On(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.Vv=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){a5.prototype.show.call(this);g.On(this.element,"ytp-show-tiles");this.player.N().o?g.En(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.yL(this.player,!1);d5(this)?(e5(this),2===this.videoData.autonavState?g.Q(this.player.N().experiments,"fast_autonav_in_background")&&3===this.player.getVisibilityState()?$4(this.u,!0):X4(this.u):3===this.videoData.autonavState&&Z4(this.u)):(g.yL(this.player,!0),e5(this))};
g.h.hide=function(){a5.prototype.hide.call(this);Z4(this.u);e5(this)};
g.h.yN=function(a){g.Dp(a)===this.element&&this.qg()};
g.h.qg=function(){if(this.suggestions&&this.suggestions.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.LL(this.aa,!0,this.aa.isFullscreen()),b=g.YC(this.aa);b&&(b=b.hc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Pd(a.width/m||1,1,1.21);n*=g.Pd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Ph(a,m,n);g.wh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;V4(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",d5(this));e5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),p=g.Qd(p+this.A,l),0!==t){u=this.stills[c];u||(u=new b5(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var B=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-z-4,E=Math.floor(m*(f+t)/b)-B-4;g.Fh(u.element,B,z);g.Ph(u.element,E,D);g.wh(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",1===t);g.K(u.element,"ytp-videowall-still-large",
2<t);t=u;p=this.suggestions[p];t.suggestion!==p&&(t.suggestion=p,u=t.api.N(),z=g.Mn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",V4(t,p,z),g.Ax(u)&&(u=p.Sh(),u=g.Bd(u,g.JD({},"emb_rel_end")),t.ha("url",u)),(p=(p=p.Lb)&&p.itct)&&g.YL(t.api,t.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ve(e.element),g.Ie(e);this.stills.length=c}};
g.h.qH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=Vta(this,a),this.videoData=a,this.qg())};
g.h.oH=function(){this.A+=this.stills.length;this.qg()};
g.h.pH=function(){this.A-=this.stills.length;this.qg()};
g.h.jy=function(){return!!this.u.w};
g.h.Hs=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,Y4(this.u),this.Fa()&&this.qg()):(this.C=!0,this.Fa()&&d5(this)&&(2===a?X4(this.u):3===a&&Z4(this.u)))};
g.h.nH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.$L(this.aa,this.stills[a].element,!0);this.Hs(1)}else this.B=null,this.C=!1;this.qg()};
g.h.Gs=function(){return this.Fa()&&d5(this)};g.r(f5,g.gM);g.h=f5.prototype;g.h.Hy=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Wta(this.player)||b;var c=a.Hi||g.Jx(a.Na),d=g.oT(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Gy=function(){return this.endScreen.Gs()};
g.h.ZF=function(){return this.Gy()?this.endScreen.jy():!1};
g.h.X=function(){g.iR(this.player.app,"endscreen",void 0);g.gM.prototype.X.call(this)};
g.h.load=function(){g.gM.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.gM.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.mH=function(a){this.Hy()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.NK=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.JB=function(){g.iR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.ZD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.ZD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.QL(this.player,[a,b])};g.vM.endscreen=f5;})(_yt_player);
